In [1]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

inputs = [0.5, -0.2, 0.1]
targets = [0.4]
test_w_i_h = np.array([[0.1, 0.4, -0.3], 
                       [-0.2, 0.5, 0.2]])
test_w_h_o = np.array([[0.3, -0.1]])



print("mnorzenie macierzy")
print(inputs*test_w_i_h)

print("suma")
print(sum(inputs*test_w_i_h))

print("wagi.T")
print(test_w_i_h.T)

print("inne")
np.dot(inputs, test_w_i_h.T)

mnorzenie macierzy
[[ 0.05 -0.08 -0.03]
 [-0.1  -0.1   0.02]]
suma
[-0.05 -0.18 -0.01]
wagi.T
[[ 0.1 -0.2]
 [ 0.4  0.5]
 [-0.3  0.2]]
inne


array([-0.06, -0.18])

In [36]:
q=2.1
print(q)

2.1


In [37]:
a = [2, 4, 5]
print(a)
b = [2.1, 5.6, -9.23]
print(b)
c = [a, b]
print(c)

[2, 4, 5]
[2.1, 5.6, -9.23]
[[2, 4, 5], [2.1, 5.6, -9.23]]


In [2]:
9/2

4.5